-- 코드를 작성해주세요
# 3세대 대장균의 ID를 출력하기
# ID 오름차순 정렬 

# 재귀? 
WITH RECURSIVE GENERATION AS(
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT CHILD.ID, CHILD.PARENT_ID, PARENT.GEN+1
    FROM ECOLI_DATA CHILD, GENERATION PARENT
    WHERE CHILD.PARENT_ID = PARENT.ID
)

SELECT ID 
FROM GENERATION
WHERE GEN = 3
ORDER BY ID ASC;