WITH RECURSIVE GENS AS(
    SELECT ID, PARENT_ID, 1 AS GEN 
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL 
    
    UNION ALL 
    
    SELECT C.ID, C.PARENT_ID, P.GEN+1 
    FROM GENS P JOIN ECOLI_DATA C ON P.ID = C.PARENT_ID 
)

SELECT ID
FROM GENS 
WHERE GEN = 3; 