-- 코드를 작성해주세요
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I LEFT JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID -- 내가 PARENT가 될 수 있으면 끝이 아니지 
WHERE T.ITEM_ID IS NULL
ORDER BY I.ITEM_ID DESC;