-- 코드를 작성해주세요
-- 물고기의 종류 별 물고기의 이름과 잡은 수를 출력

SELECT T.FISH_COUNT, N.FISH_NAME
FROM FISH_NAME_INFO N 
    JOIN 
    (SELECT FISH_TYPE, COUNT(ID) AS FISH_COUNT
        FROM FISH_INFO 
        GROUP BY FISH_TYPE) T 
    ON N.FISH_TYPE = T.FISH_TYPE
ORDER BY T.FISH_COUNT DESC;