-- 코드를 입력하세요
-- 0건인 시간대도 함께 출력해야 됨 
WITH T1 AS (
    SELECT 0 AS HOUR UNION ALL 
    SELECT 1 UNION ALL  
    SELECT 2 UNION ALL 
    SELECT 3 UNION ALL 
    SELECT 4 UNION ALL 
    SELECT 5 UNION ALL 
    SELECT 6 UNION ALL 
    SELECT 7 UNION ALL 
    SELECT 8 UNION ALL 
    SELECT 9 UNION ALL 
    SELECT 10 UNION ALL 
    SELECT 11 UNION ALL 
    SELECT 12 UNION ALL 
    SELECT 13 UNION ALL 
    SELECT 14 UNION ALL 
    SELECT 15 UNION ALL 
    SELECT 16 UNION ALL 
    SELECT 17 UNION ALL 
    SELECT 18 UNION ALL 
    SELECT 19 UNION ALL 
    SELECT 20 UNION ALL 
    SELECT 21 UNION ALL 
    SELECT 22 UNION ALL 
    SELECT 23
)

# SELECT T2.HOUR, COUNT(IFNULL(ANIMAL_ID, 0)) AS 'COUNT'
# SELECT T1.HOUR, COUNT(IFNULL(T2.ANIMAL_ID, 0)) AS 'COUNT'
SELECT T1.HOUR, SUM(CASE WHEN ANIMAL_ID IS NOT NULL THEN 1 ELSE 0 END) AS 'COUNT'
FROM T1 LEFT JOIN ( SELECT HOUR(DATETIME) AS HOUR, ANIMAL_ID 
                    FROM ANIMAL_OUTS 
                    ) AS T2 
    ON T1.HOUR = T2.HOUR
# GROUP BY T2.HOUR -- T1의 HOUR로 그룹핑해야 0,1,2,3... 전부 뜬다 
GROUP BY T1.HOUR
ORDER BY T1.HOUR;