-- 코드를 입력하세요
-- 완료된 중고 거래의 총금액이 70만 원 이상인 사람의 회원 ID, 닉네임, 총거래금액을 조회
SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM (SELECT *, SUM(PRICE) AS TOTAL_SALES
      FROM USED_GOODS_BOARD JOIN USED_GOODS_USER ON WRITER_ID = USER_ID 
      WHERE STATUS = 'DONE'
      GROUP BY USER_ID 
      ) AS T
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC; 

# SELECT USER_ID, NICKNAME, PRICE
# FROM USED_GOODS_BOARD JOIN USED_GOODS_USER ON WRITER_ID = USER_ID 
# WHERE STATUS = 'DONE' AND PRICE >= 700000
# GROUP BY USER_ID
# ORDER BY PRICE ASC; 