-- 코드를 입력하세요
# 만원 단위의 가격대 별 - 상품 개수 구하기 
# 가격을 1만으로 나눈 몫을 컬럼으로 갖기  

# SELECT PRODUCT_ID, PRICE, FLOOR(PRICE/10000) AS PRICE_GROUP 
# FROM PRODUCT
# ORDER BY PRICE_GROUP ;
     
     
SELECT PRICE_GROUP*10000 AS 'PRICE_GROUP', COUNT(PRODUCT_ID) AS 'PRODUCTS'
FROM (SELECT PRODUCT_ID, FLOOR(PRICE/10000) AS PRICE_GROUP 
     FROM PRODUCT ) AS T
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP ASC; 
     
